### ISSUE TITLE
Call graph of SUPA

### ISSUE THREAD

**Issue by rainoftime** [SVF-tools/SUPA#2]
How does SUPA make use of the call graph produced by the pre-analysis (Andersen's analysis)?
1. Construct a new call graph on-the-fly
2. Refine existing call graph

If the first strategy is taken, will SUPA generate constraints based on the pre-built call graph? What if SUPA run out of the time budget?

**Comment by yuleisui** [comment]
Connecting interprocedural value-flow edges for indirect calls on-the-fly:
https://github.com/SVF-tools/SUPA/blob/6a1f16fdf1f1c30e477865d2294fdfa2897c8f13/include/DDA/FlowDDA.h#L96

However, the on-the-fly callgraph has an upper bound, i.e., the pre-computed one by Andersen in order to shrink the search space during graph traversal:

https://github.com/SVF-tools/SUPA/blob/6a1f16fdf1f1c30e477865d2294fdfa2897c8f13/include/DDA/DDAVFSolver.h#L394

**Comment by rainoftime** [comment]
Thank! I thought that SUPA tries to build a new call graph on the fly, but will use the pre-computed one by Andersen if some budget is reached. 
However, from the function `resolveFunPtr` in `DDAVFSolver.h`,  it seems that SUPA will deal with different call sites (`isCallSiteRetSVFGNode` or  `isFunEntrySVFGNode`) with different strategies?  For the latter kind, it will directly use the pre-computed one by Andersen?

**Comment by yuleisui** [comment]
There is only one strategy. The two branches represent two scenarios when we see a DPMItem. 

When travelling to the entry of a function, we will use Andersen's analysis to get an upper bound (approximation) of the caller targets and then refine the targets based on the dynamic programming traversal to get the precise results.
