### ISSUE TITLE
Does SUPA support DDA for ObjSym?

### ISSUE THREAD

**Issue by kren1** [SVF-tools/SUPA#4]
Does SUPA support analysis of abstract memory objects? For example if I run:

`/dvf -cxt -query='7256 7257' -cpts -print-query-pts m4.bc`

I get:

```
<7256 [: ]>  ==> { <7257 [: ]>  }         
##<endp> Source Loc:                          
Ptr 7256                PointsTo: { 7257 }               
!!Target NodeID 7257     [<endp> Source Loc: ] 
```

Which is informing me that the top level pointer 7256 is pointing to abstract object 7257. But it completely skips 7252. There is some code here, that skips all non top level pointers. So I'm wondering if this is a fundamental limitation or am I using it wrong?

For reference running `wpa 'print-all-pts -ander m4.bc` yields

```
Ptr 7256    PointsTo: { 7257 }          
!!Target NodeID 7257   [<endp> Source Loc: ] 
```
and
```
Ptr 7257    PointsTo: { 1 }      
!!Target NodeID 1  [Dummy Obj id: 1]   
```

on relevant pointers.

Thanks!

**Comment by yuleisui** [comment]
Unfortunately, SUPA now only supports querying top-level pointers (llvm values). Top-level pointers are uniquely defined in the program and memory object needs to be qualified by a program location.

May I know why you would like to query a memory object? Querying pointers would be enough for all practical usage scenarios.

**Comment by kren1** [comment]
Thanks for the quick response.

My usage scenario is grouping memory objects into self-aliasing groups.

I don't entirely understand your point about memory objects needing to be qualified by a program location. Can't they be defined in terms of the llvm::Value of their allocation site?

**Comment by yuleisui** [comment]
> Thanks for the quick response.
> 
> My usage scenario is grouping memory objects into self-aliasing groups.
> 
> I don't entirely understand your point about memory objects needing to be qualified by a program location. Can't they be defined in terms of the llvm::Value of their allocation site?

For flow-sensitive analysis, like SUPA, an abstract memory object (address-taken variable) can be defined multiple times  via stores at different program points. Top-level variables ("%" in LLVM IR) are uniquely defined.

```
1: p = &a
2: *p = &b
3: *p = &c
```

Object "a" at line 2 and 3 has different points-to values, i.e., "b" and "c", by flow-sensitive analysis.

For grouping memory objects, I would suggest looking at https://github.com/SVF-tools/SVF/blob/master/lib/MSSA/MemRegion.cpp and https://github.com/SVF-tools/SVF/blob/master/lib/MSSA/MemPartition.cpp based on Andersen's flow-insensitive analysis.

Another way I can think of is to query pointers at loads/stores and then group loads/stores instead of querying points-to results of memory objects.

Let me know if any questions.

**Comment by kren1** [comment]
I see thanks for the explanation and your suggestions. I'll look into those.
